version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "4317:4317" # OTel OTLP gRPC, needs COLLECTOR_OTLP_ENABLED
      - "4318:4318" # OTel OTLP HTTP, needs COLLECTOR_OTLP_ENABLED
      - "5775:5775/udp" # zipkin thrift (deprecated 2016)
      - "5778:5778" # sdk configs
      - "6831:6831/udp" # thrift compact
      - "6832:6832/udp" # thrift binary, for NodeJS clients
      - "9411:9411" # zipkin thrift
      - "14250:14250" # jaegar agent gRPC
      - "14268:14268" # thrift binary
      - "14269:14269" # Collector admin at /metrics health at /
      - "16686:16686" # Web UI
    networks:
      - default

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"